spring:
  application:
    name: simple-form-login
  datasource:
    url: jdbc:h2:mem:formlogin
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true